### ISSUE TITLE
Does not work for spotify.link URLs

### ISSUE THREAD

**Issue by wrussell1999** [danielfspencer/playlist-bot#1]
Spotify now uses both `open.spotify.com` and `spotify.link`. Currently only detects `open.spotify.com` URLs.

**Comment by wrussell1999** [comment]
As `spotify.link` is a URL redirect, you can solve this with the following:
```python
import requests
r = requests.get("https://spotify.link/UWZD92oeWDb")
print(r.url) # https://open.spotify.com/track/4lSmHyczglfsTh0lYjNoSj?si=FexOcvXbSB64aaAinVCu4w&utm_source=copy-link&utm_medium=copy-link&nd=1&_branch_match_id=link-1242370132819421250
```

and then run through the normal process.

**Comment by danielfspencer** [comment]
Resolved by https://github.com/danielfspencer/playlist-bot/pull/2
